# example netlify.toml
[build]
  command = ""
  functions = "netlify/functions"
  publish = "."

# What the deploy button requests to run
[template.environment]
  ORBIT_WORKSPACE = "ORBIT_WORKSPACE: usually found in the URL for your dashboard"
